# Generated by Django 4.2.7 on 2026-01-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_admin_user_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                ("lost_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=200)),
                ("item_type", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="lost_items/"),
                ),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=20
                    ),
                ),
                (
                    "reporter_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("FACULTY", "Faculty"),
                            ("STAFF", "Staff"),
                            ("VISITOR", "Visitor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOST", "Lost"),
                            ("FOUND", "Found"),
                            ("RETURNED", "Returned"),
                        ],
                        default="LOST",
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_items",
                        to="core.category",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
