# Generated by Django 4.2.7 on 2026-07-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lostitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="condition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="date_lost_found",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="distinguishing_features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="report_images/"),
        ),
        migrations.AddField(
            model_name="report",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="report_images/"),
        ),
        migrations.AddField(
            model_name="report",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="report_images/"),
        ),
        migrations.AddField(
            model_name="report",
            name="item_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="time_lost_found",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="core.item",
            ),
        ),
    ]
