# Generated by Django 4.2.7 on 2025-11-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="claim_evidence/"
                    ),
                ),
                ("claim_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="users.student",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "claim",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="claim_status_2f2888_idx"),
                    models.Index(
                        fields=["claimed_by"], name="claim_claimed_83a99a_idx"
                    ),
                ],
                "unique_together": {("item", "claimed_by")},
            },
        ),
    ]
