# Generated by Django 4.2.7 on 2025-11-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("categories", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Lost", "Lost"),
                            ("Found", "Found"),
                            ("Returned", "Returned"),
                            ("Unclaimed", "Unclaimed"),
                        ],
                        default="Found",
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("Found", "Found"), ("Lost", "Lost")], max_length=10
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(blank=True, null=True, upload_to="evidence/"),
                ),
                ("reported_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="categories.category",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="locations.location",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_items",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "db_table": "item",
                "ordering": ["-reported_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "item_type"], name="item_status_aec2a9_idx"
                    ),
                    models.Index(fields=["category"], name="item_categor_33fe10_idx"),
                    models.Index(fields=["location"], name="item_locatio_e8412e_idx"),
                ],
            },
        ),
    ]
